
<script type="text/javascript">
    require(['jquery'], function(jQuery) {
        var ls = (function(a) {
            if(a == '') {
                return {}
            }
            
            var b = {};
            
            for(var i = 0; i < a.length; ++i) {
                var p=a[i].split('=', 2);
                
                if(p.length == 1)
                    b[p[0]] = '';
                else
                    b[p[0]] = decodeURIComponent(p[1].replace(/\+/g, ' '));
            }
            
            return b;
        })(window.location.search.substr(1).split('&'));
        
        if(parseInt(ls['subscribe']) === 1) {
            var select = jQuery('.product-custom-option[name="options[<?php echo \Toppik\Subscriptions\Model\Preferences::SUBSCRIPTION_OPTION_ID?>]"]');
            
            select.find('option').each(function() {
                var value = jQuery(this).val();
                
                if(!isNaN(value) && parseInt(Number(value)) == value && !isNaN(parseInt(value, 10))) {
                    select.val(value);
                    return false;
                }
            });
        }
    });
</script>
