<?php
/* @var \Toppik\Subscriptions\Block\Checkout\Cart\Form\Upgrade $block */
?>
<div class="content">
    <h6><?php echo __('SAVE 10%') ?></h6>
    <p><?php echo __('Select to receive auto-delivery every 30, 45, 60, 90, or 120 days to receive 10% off every order and free shipping.') ?></p>
    <p class="desctop"><?php echo __('Convenient & easy | Cancel any time | Free to join') ?></p>

    <div class="mobile">
        <ul>
            <li><p><?php echo __('Convenient & easy') ?></p></li>
            <li><p><?php echo __('Cancel any time') ?></p></li>
            <li><p><?php echo __('Free to join') ?></p></li>
        </ul>
    </div>

    <div class="buttons">
        <a href="#" class="lightbox-light button action primary" rel="cart-edit" data-type="lightbox" data-callback="updateFormAction"><?php echo __('Save Now') ?></a>
    </div>
</div>
