<?php
	$profile = $block->getProfile();
?>

<div class="page-title title-buttons clearfix">
    <h1><?php echo $this->getTitle()?></h1>
</div>

<div class="order-info">
    <div><?php echo __('Subscription Information') ?></div>
    <div id="order-info-tabs">
        <div class="current" style="margin-right: 20px"><strong><?php echo __('Items Qty')?></strong></div>
        <div><?php echo $this->getProfile()->getItemsQty()?></div>
    </div>
</div>

<div class="form-options">
    <h6><?php echo __('Choose An Option')?></h6>
    
	<form action="<?php echo $this->getUrl('subscriptions/customer/updatePost', ['_secure' => true])?>" method="post">
		<?php echo $block->getBlockHtml('formkey')?>
		<input type="hidden" name="id" value="<?php echo $profile->getId() ?>" />
		<input type="hidden" name="action_type" value="product" />
        
        <select class="common-input product-input" name="product">
            <option></option>
            
            <?php foreach($block->getProductCollection() as $_group_name => $_groups):?>
                <optgroup label="<?php echo $_group_name?>">
                    <?php foreach($_groups as $_name => $_product):?>
                        <option value="<?php echo $_product->getId()?>"><?php echo sprintf('%s: %s', $_product->getName(), $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($_product->getFinalPrice(), 2), true, false))?></option>
                    <?php endforeach?>
                </optgroup>
            <?php endforeach?>
        </select>
        
		<button type="submit" class="action primary button"><?php echo __('Save')?></button>
	</form>
</div>
