

<?php
	$profile = $this->getProfile();
?>

<div class="page-title title-buttons clearfix">
    <h1><?php echo $this->getTitle()?></h1>
</div>

<div class="order-info">
    <dt><?php echo __('Subscription Information') ?></dt>
        <div id="order-info-tabs">
            <div class="current" style="margin-right: 20px"><strong><?php echo __('Items Qty')?></strong></div>
            <div><?php echo $this->getProfile()->getItemsQty()?></div>
        </div>
</div>

<div class="form-options">
    <h6><?php echo __('Choose An Option')?></h6>
    
	<form action="<?php echo $this->getUrl('subscriptions/customer/updatePost', ['_secure' => true])?>" method="post">
		<?php echo $block->getBlockHtml('formkey')?>
		<input type="hidden" name="id" value="<?php echo $profile->getId() ?>" />
		<input type="hidden" name="action_type" value="quantity" />
		
        <?php foreach($this->getProfile()->getAllVisibleItems() as $_item):?>
            <?php if($this->getProfile()->canEditQuantityOfItem($_item)):?>
                <dl>
                    <dt><?php echo sprintf('%s (%s)', $_item->getName(), $_item->getSku())?></dt>
                    
                    <dd>
                        <select class="common-input quantity-input" id="item_qty_<?php echo $_item->getId()?>" name="item_qty[<?php echo $_item->getId()?>]">
                            <?php $i = 0; while(++$i <= 10): ?>
                                <option value="<?php echo $i ?>"<?php if((int) $_item->getQty() === $i) echo ' selected="selected"' ?>><?php echo $i ?></option>
                            <?php endwhile ?>
                        </select>
                    </dd>
                </dl>
            <?php endif?>
        <?php endforeach?>
        
		<button type="submit" class="action primary button"><?php echo __('Save')?></button>
	</form>
</div>
